### ISSUE TITLE
Styling raises AttributeError in python 3.11.1 due to CPython regression

### ISSUE THREAD

**Issue by edrogers** [JoshKarpel/counterweight#80]
I happened to use python 3.11.1, and couldn't get your examples to work. Tinkering for a bit led me down a rabbit hole, whereupon I came to learn of a curious regression for that micro version of CPython: https://github.com/python/cpython/issues/100098 

This affects the `BorderKind` class, as its [an Enum of NamedTuple values](https://github.com/JoshKarpel/counterweight/blob/c7506120bfc224c4a42b799294dad25f3dc393cc/counterweight/styles/styles.py#L263). I'll be making a PR to address this shortly

**Comment by JoshKarpel** [comment]
Woah, nice catch! Looking forward to the PR :)
